Use String format for mandatory property warning/error
devonfw/cobigen pull request #1486
Opened 2022-02-24 10:20 UTC by MikeSchumacherCapgemini

Changed the way error messages/warnings are done in the openapiplugins constants, using string format.

2022-02-24 13:14 UTC, maybeec approved these changes

2022-02-24 14:36 UTC, maybeec commented
@MikeSchumacherCapgemini, there are failing tests, please have a look

2022-02-25 07:52 UTC, maybeec requested changes

2022-02-25 07:52 UTC, maybeec commented on cobigen-plugins/cobigen-openapiplugin-parent/cobigen-openapiplugin/src/main/java/com/devonfw/cobigen/openapiplugin/util/constants/Constants.java
> +          "Please add the required attribute in your input file or set the \"mandatory\" attribute to \"false\".");
This will produce `propertyPlease`

2022-02-25 08:18 UTC, maybeec approved these changes

2022-02-25 08:19 UTC, MikeSchumacherCapgemini commented on cobigen-plugins/cobigen-openapiplugin-parent/cobigen-openapiplugin/src/main/java/com/devonfw/cobigen/openapiplugin/util/constants/Constants.java
> +          "Please add the required attribute in your input file or set the \"mandatory\" attribute to \"false\".");
You are right, i added a whitespace now

2022-02-25 08:49 UTC, merged