use annotations of the patchfile, if javamerge_override is set.
devonfw/cobigen pull request #1490
Opened 2022-03-01 11:13 UTC by LarsReinken

Adresses/Fixes #430

Implements
tests with annotations
use classannotation of the patchfile, if javamerge_override is set.

@devonfw/cobigen

2022-05-05 12:07 UTC, jan-vcapgemini requested changes

2022-05-09 08:45 UTC, maybeec approved these changes

2022-05-09 11:54 UTC, jan-vcapgemini approved these changes

2022-05-09 11:54 UTC, jan-vcapgemini commented on cobigen-plugins/cobigen-javaplugin-parent/cobigen-javaplugin/src/main/java/com/devonfw/cobigen/javaplugin/merger/JavaMerger.java
> +  /**
There is still a description for the method missing. But it can be added later too.

2022-05-10 06:52 UTC, merged