Adjust documentation
devonfw/cobigen pull request #1491
Opened 2022-03-02 12:30 UTC by GuentherJulian

Adresses #1359

@devonfw/cobigen

2022-03-02 15:41 UTC, jan-vcapgemini requested changes

2022-03-02 15:41 UTC, jan-vcapgemini commented on documentation/Home.asciidoc
> +* Generation of an **Ionic** client with full `CRUD` operations connected a devon4j server based on link:https://github.com/devonfw/devon4ng-ionic-application-template[devon4ng Ionic template].
... connected "to" a ...

2022-03-02 15:41 UTC, jan-vcapgemini commented on documentation/Home.asciidoc
> +* Generation of a **`EXT JS` 6** client with full `CRUD` operations connected a devon4j server.
... connected "to" a ...

2022-03-02 16:01 UTC, maybeec submitted a review, later dismissed

2022-03-03 10:43 UTC, MikeSchumacherCapgemini requested changes

2022-03-04 11:06 UTC, jan-vcapgemini approved these changes

2022-03-04 19:02 UTC, maybeec approved these changes
Thank you very much for your detailed improvements

2022-03-10 10:09 UTC, MikeSchumacherCapgemini approved these changes

2022-03-10 10:09 UTC, merged