#1532 fixed HealthCheck not being able to handle a conflict with the old and new configuration
devonfw/cobigen pull request #1533
Opened 2022-05-10 15:39 UTC by jan-vcapgemini

Adresses/Fixes #1532.

Implements
* added new ConfigurationConflictException
* replaced InvalidConfigurationException with ConfigurationConflictException in checkForConflict method
* replaced InvalidConfigurationException with ConfigurationConflictException in testConflictConfiguration test
* added new case for conflicted configurations to ExceptionHandler handle method
* added catch of ConfigurationConflictException with adjusted message to healthCheckDialog execute

@devonfw/cobigen

2022-05-10 15:55 UTC, mdukhan submitted a review, later dismissed

2022-05-10 16:10 UTC, GuentherJulian approved these changes

2022-05-10 17:57 UTC, maybeec requested changes

2022-05-11 08:35 UTC, jan-vcapgemini commented on cobigen-eclipse/cobigen-eclipse/src/com/devonfw/cobigen/eclipse/common/tools/ExceptionHandler.java
> +      LOG.warn("Conflicted configuration.", e);
Adjusted.

2022-05-11 09:07 UTC, maybeec approved these changes

2022-05-11 09:31 UTC, merged