1531 inform the user about deprecation and upgrade options
devonfw/cobigen pull request #1541
Opened 2022-06-08 17:36 UTC by mdukhan

Adresses/Fixes #1531 

Implements

* Generation CLI DeprecatedMonolithicTemplatesException Handler 

@devonfw/cobigen

2022-06-20 08:51 UTC, jan-vcapgemini requested changes

2022-06-20 08:51 UTC, jan-vcapgemini commented on cobigen-cli/cli/src/main/java/com/devonfw/cobigen/cli/commands/GenerateCommand.java
> +          + "type yes/y to continue or no/n to cancel (or hit return for yes).", System.getProperty("user.dir"));
We should remove the printStackTrace and add the exception to the info or maybe another warning message.

2022-06-20 08:51 UTC, jan-vcapgemini commented on cobigen-cli/cli/src/main/java/com/devonfw/cobigen/cli/commands/GenerateCommand.java
> +   */
Better description: Uses default initialization, checks if old templates exist, handles the exception and lets the user decide if the templates should be upgraded.
Extra returns can be removed too.

2022-06-20 08:51 UTC, jan-vcapgemini commented on cobigen-cli/cli/src/main/java/com/devonfw/cobigen/cli/utils/CobiGenUtils.java
> +   * Registers CobiGen plug-ins and instantiates CobiGen, even if Old templates found
Old can be lowercase.

2022-06-23 14:41 UTC, mdukhan commented
#

2022-06-23 14:41 UTC, closed without merging