# 1521 Attached Template-set plugin for deployment
devonfw/cobigen pull request #1562
Opened 2022-08-04 12:34 UTC by Ali7223

Adresses/Fixes #1521
this PR continues and replaces the old [PR](https://github.com/devonfw/cobigen/pull/1559)

Implements

* Implemented attached artifact for each template set
 

@devonfw/cobigen

2022-08-04 13:49 UTC, Ali7223 commented
Build does not work because of missing template-set.xml files and the draft is waiting for the files first to get merged.

2022-08-10 11:51 UTC, jan-vcapgemini commented on cobigen-templates/crud-angular-client-app/pom.xml
> +                  <file>${basedir}\src\main\resources\template-set.xml</file>
Shouldn't this be in src/main/templates?

2022-08-10 15:35 UTC, EduardKrieger commented
Add template-set to the end of the artifact name and relocate the attach process to the templates parent pom

2022-08-18 11:29 UTC, Zylesto approved these changes

2022-08-22 08:54 UTC, jan-vcapgemini approved these changes

2022-08-22 11:15 UTC, ZakariaeMkassi approved these changes

2022-08-25 09:49 UTC, Ali7223 commented
> Can you also add template-set at the end to the created artifacts. Also the template-set merge will be creating the xml files but i think there is no problem in already adding empty files @jan-vcapgemini ?

'Can you also add template-set at the end to the created artifacts'
Done

2022-08-25 10:50 UTC, Zylesto approved these changes

2022-08-25 11:19 UTC, EduardKrieger approved these changes

2022-08-26 09:25 UTC, jan-vcapgemini approved these changes

2022-08-28 12:27 UTC, maybeec requested changes
Strangely I see a lot of emtpy files in the PR.
What is this about?

2022-08-29 09:36 UTC, Ali7223 commented
> Strangely I see a lot of emtpy files in the PR. What is this about?

I was testing if the project builds and these files were deployed seperately. 

All of the empty files have been removed.

2022-08-29 10:08 UTC, jan-vcapgemini commented
> Strangely I see a lot of emtpy files in the PR. What is this about?

I thought they were required because the profile attach-artifacts activation only works if a template-set.xml is existing. The empty files will be filled when the merge ticket is done and the final template-set.xml can be implemented.

2022-09-04 12:34 UTC, maybeec approved these changes

2022-09-04 12:34 UTC, merged