Update mgmt_ide-setup.asciidoc
devonfw/cobigen pull request #1575
Opened 2022-09-08 12:12 UTC by jan-vcapgemini

fixed devonfw ide link
converted 7, 8 to substeps of 6
added git longpaths configuration step

Adresses/Fixes #<ISSUENO>.

Implements

* 
* 
* 

@devonfw/cobigen

2022-09-08 17:10 UTC, maybeec requested changes

2022-09-08 17:10 UTC, maybeec commented on documentation/mgmt_ide-setup.asciidoc
> +8. Now open eclipse using the eclipse-main.bat file or by executing `devon eclipse` on the console and import the CobiGen projects you want to work on
Simply use dot without number.
Asciidoc will automatically create enumeration

2022-09-09 08:02 UTC, EduardKrieger requested changes

2022-09-09 10:10 UTC, EduardKrieger approved these changes

2022-09-14 08:23 UTC, maybeec approved these changes

2022-09-19 10:50 UTC, merged