initial commit
devonfw/cobigen pull request #1577
Opened 2022-09-09 15:52 UTC by EduardKrieger

Adresses/Fixes #1476.
Initial version to cache the dependencies more efficient and less error prone.

Implements

* generatePomFileHash reworked also takes m2 repo into account.
* first version of a validateCache function to check the cache.

@devonfw/cobigen

2022-09-16 09:45 UTC, jan-vcapgemini requested changes

2022-09-16 09:45 UTC, jan-vcapgemini commented on cobigen/cobigen-core-api/src/main/java/com/devonfw/cobigen/api/util/MavenUtil.java
> +          LOG.warn(String.format("Cache %s pointing to another maven Repository, this could cause some problems",
Better use: LOG.warn("Cache {} pointing to another maven Repository, this could cause some problems", cp);

2022-09-16 09:45 UTC, jan-vcapgemini commented on cobigen/cobigen-core-api/src/main/java/com/devonfw/cobigen/api/util/MavenUtil.java
> +          LOG.error(String.format("Cache %s is outdated dependency needs to be resolved or downloaded", cp.toString()));
Better use: LOG.warn("Cache {} pointing to another maven Repository, this could cause some problems", cp);

2022-12-01 08:02 UTC, EduardKrieger commented
Closed because the branch is using the wrong base, switched to new PR #1613

2022-12-01 08:02 UTC, EduardKrieger commented
Closed because the branch is using the wrong base, switched to new PR #1613

2022-12-01 08:02 UTC, closed without merging