#1530 added maven settings password decryption
devonfw/cobigen pull request #1583
Opened 2022-09-21 09:30 UTC by jan-vcapgemini

Adresses/Fixes #1530 #1517.

Implements

* added org.codehaus.plexus sec-dispatcher dependency
* added org.codehaus.plexus cipher dependency
* added MavenSettingsUtil
* added MavenSettingsUtilTest and resources
* made sure that only template-set.xml files get returned as download links
* added basic authentication

@devonfw/cobigen

2022-09-21 20:15 UTC, maybeec requested changes
Is there a reason why you put this code into api bundle? I don't see any plugin making use of this code as this should be even hidden from plugin development.

2022-09-22 05:48 UTC, Zylesto approved these changes

2022-09-28 14:03 UTC, Zylesto approved these changes

2022-10-25 09:45 UTC, jan-vcapgemini commented
This PR is not needed anymore as all of the changes were added to #1585 already.

2022-10-25 09:45 UTC, closed without merging