#1495 All changes in one commit
devonfw/cobigen pull request #1597
Opened 2022-10-27 13:13 UTC by KHucklenbroich

Adresses/Fixes #<ISSUENO>.

Check https://github.com/devonfw/cobigen/pull/1558
#1558 
Implements

Requests made until 24.10.2022 are taken into account.

* 
* 
* 

@devonfw/cobigen

2023-01-06 12:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/cobigen?pullRequest=1597) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/cobigen?pullRequest=1597) before we can accept your contribution.<br/>**4** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: mdukhan<br/>:white_check_mark: jan-vcapgemini<br/>:white_check_mark: Lur1an<br/>:white_check_mark: EduardKrieger<br/>:x: KHucklenbroich<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/cobigen?pullRequest=1597) it.</sub>

2023-01-20 16:55 UTC, EduardKrieger requested changes

2023-01-20 16:55 UTC, EduardKrieger commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/reader/ContextConfigurationReader.java
> +    // TODO: check if this is still needed
open TODO

2023-01-20 16:55 UTC, EduardKrieger commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/entity/Matcher.java
> +   * @param accumulationType2 of the matcher
Change back to accumulationType

2023-01-20 16:55 UTC, EduardKrieger commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/entity/Matcher.java
> +  private String accumulationType;
Change back to accumulationType

2023-01-20 16:55 UTC, EduardKrieger commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/constant/TemplateSetConfigurationVersion.java
> +   * Initial release.
Maybe also say that this a templateSet merged the old configurations together

2023-01-20 16:55 UTC, EduardKrieger commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/constant/TemplateSetConfigurationVersion.java
> +   * Get latest context configuration version supported by this CobiGen release.
template set

2023-01-20 16:55 UTC, EduardKrieger commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/reader/TemplateSetConfigurationReader.java
> +  // TODO: Use dependency injection here instead of the new operator
open TODO

2023-01-24 12:26 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/reader/AbstractContextConfigurationReader.java
>  public abstract class AbstractContextConfigurationReader {
Good question, I think it is not needed anymore and can be moved into the ContextConfigurationReader.

2023-01-24 12:29 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/constant/TemplateSetConfigurationVersion.java
> +  v6_0(1f, false);
I think we should change this version to v1_0 instead. This is the first template-set version and it does not make sense to initialize it with v6_0.

2023-01-24 12:31 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/constant/TemplateSetConfigurationVersion.java
> +  v6_0(1f, false);
The only "problem" I see is that we need to change this version in all template-set.xmls then...

2023-03-13 12:22 UTC, merged