1595 extend uprader to upgrade from monolithic structure to template set.xml
devonfw/cobigen pull request #1611
Opened 2022-11-30 17:09 UTC by quantumfate

Adresses/Fixes #1595 .

Implements

* merge from context.xml and template.xml
* context.xml will be deleted and adapted to new template-set.xml

@devonfw/cobigen

2022-11-30 17:10 UTC, quantumfate commented
[The old PR](https://github.com/devonfw/cobigen/pull/1610)

2023-01-04 07:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/cobigen?pullRequest=1611) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/cobigen?pullRequest=1611) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: Lur1an<br/>:white_check_mark: maybeec<br/>:white_check_mark: EduardKrieger<br/>:x: quantumfate<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/cobigen?pullRequest=1611) it.</sub>

2023-03-30 16:10 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/reader/ContextConfigurationReader.java
> +   * @param isTemplateSet TODO
Javadoc missing.

2023-03-30 21:40 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/upgrade/AbstractConfigurationUpgrader.java
> +  protected static final Logger LOG = LoggerFactory.getLogger(AbstractConfigurationUpgrader.class);
Needs to be private.
Every Class needs its own logger.

2023-03-30 21:44 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/upgrade/TemplateConfigurationUpgrader.java
> +        // upgrade from v5 to v6 will be handles by context configuration upgrader cause of files merge
comment needs to be adjusted.

2023-03-30 21:46 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/upgrade/TemplateSetUpgrader.java
> +   *         {@link com.devonfw.cobigen.impl.config.entity.io.v6_0.ContextConfiguration} as key and a {@link Path} for
There is no v6 ContextConfiguration anymore.

2023-03-30 21:47 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/upgrade/TemplateSetUpgrader.java
> +  public Map<TemplateSetConfiguration, Path> upgradeTemplatesToTemplateSetsV6(Path templatesLocation) throws Exception {
V6 can be removed.

2023-03-30 21:49 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/upgrade/TemplateSetUpgrader.java
> +   * @param trigger {@link com.devonfw.cobigen.impl.config.entity.io.v6_0.Trigger} to the related template folder
Change to tsV1.

2023-03-30 21:50 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/upgrade/TemplateSetUpgrader.java
> +   * Splits a contextConfiguration and converts a {@link Trigger} and his data to a v6_0 Trigger
To v1.

2023-03-30 21:50 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/upgrade/TemplateSetUpgrader.java
> +   * @return {@link com.devonfw.cobigen.impl.config.entity.io.v6_0.ContextConfiguration} List of the split
v1.

2023-03-30 21:52 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/upgrade/TemplateSetUpgrader.java
> +   * @return {@link TemplatesConfiguration} V6 templates configuration object
V1 or V5?

2023-03-30 21:54 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/upgrade/TemplateSetUpgrader.java
> +   * @return {@link ContextConfiguration}
Throws were removed?

2023-03-30 21:58 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/test/java/com/devonfw/cobigen/unittest/config/upgrade/ContextConfigurationUpgraderTest.java
> +        TemplateSetConfigurationUpgrader tscU = new TemplateSetConfigurationUpgrader();
Variable tscU not needed.

2023-03-30 21:59 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/test/java/com/devonfw/cobigen/unittest/config/upgrade/ContextConfigurationUpgraderTest.java
> +   * Tests if v6.0 context configuration is compatible to v6.0 schema.
v1 tsc.

2023-03-30 21:59 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/test/java/com/devonfw/cobigen/unittest/config/upgrade/ContextConfigurationUpgraderTest.java
> +   * Tests if v2.1 context configuration schema is not compatible to v6.0 configuration file.
v1 tsc

2023-03-30 22:03 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/test/java/com/devonfw/cobigen/unittest/config/upgrade/TemplateSetUpgraderTest.java
> +          .upgradeTemplatesToTemplateSetsV6(this.templateLocation);
remove V6

2023-03-30 22:03 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/test/java/com/devonfw/cobigen/unittest/config/upgrade/TemplateSetUpgraderTest.java
> +        validateTemplateSetConfiguration(templateSetPath, "v6.0");
v1.0

2023-03-30 22:04 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/test/java/com/devonfw/cobigen/unittest/config/upgrade/TemplateSetUpgraderTest.java
> +        validateTemplateSetConfiguration(templateSetPath, "v6.0");
v1

2023-03-30 22:08 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/test/resources/testdata/unittest/config/upgrade/ContextConfigurationUpgraderTest/valid-v3.0/context.xml
> +<contextConfiguration xmlns="http://capgemini.com/devonfw/cobigen/ContextConfiguration" version="6.0">
v3.0

2023-03-30 22:09 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/test/resources/testdata/unittest/config/upgrade/TemplateSetUpgraderTest/valid-2.1/templates/CobiGen_Templates/src/main/templates/templateSet1/templates.xml
> +<templatesConfiguration xmlns="http://capgemini.com/devonfw/cobigen/TemplatesConfiguration" version="4.0">
Why v4?

2023-03-30 22:10 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/test/resources/testdata/unittest/config/upgrade/TemplateSetUpgraderTest/valid-2.1/templates/CobiGen_Templates/src/main/templates/templateSet2/templates.xml
> +<templatesConfiguration xmlns="http://capgemini.com/devonfw/cobigen/TemplatesConfiguration" version="5.0">
v5 is correct, but source path is still v6

2023-03-30 22:11 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/test/resources/testdata/unittest/config/upgrade/TemplatesConfigurationUpgraderTest/valid-v6.0/templates.xml
> +<templatesConfiguration xmlns="http://capgemini.com/devonfw/cobigen/TemplatesConfiguration" version="6.0">
There is no v6, resource can be removed?

2023-03-30 22:13 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/upgrade/TemplateSetUpgrader.java
> +    List<com.devonfw.cobigen.impl.tsconfig.entity.io.v1_0.ContextConfiguration> contextFiles = splitContext(
Is there a tsconfig v1_0 ContextConfiguration?

2023-03-30 22:16 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/upgrade/TemplateSetUpgrader.java
> +        Files.delete(tcPath);
What happens if the read didn't work properly and the file gets deleted anyways?

2023-03-30 22:18 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/main/java/com/devonfw/cobigen/impl/config/upgrade/TemplateSetUpgrader.java
> +  private TemplateSetConfiguration buildTemplateSetConfiguration(TemplatesConfiguration tc,
Javadoc missing.

2023-03-30 22:21 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/test/java/com/devonfw/cobigen/unittest/config/upgrade/ContextConfigurationUpgraderTest.java
> +   * Tests the valid upgrade of a context configuration from version v2.1 to template set v1.This also includes a merge
Needs a whitespace.

2023-03-30 22:21 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/test/java/com/devonfw/cobigen/unittest/config/upgrade/ContextConfigurationUpgraderTest.java
> +   * of a templateConfiguration v5.0 into a templateSetConfigration
typo

2023-03-30 22:24 UTC, jan-vcapgemini commented on cobigen/cobigen-core/src/test/java/com/devonfw/cobigen/unittest/config/upgrade/ContextConfigurationUpgraderTest.java
> +   * Tests if v6.0 context configuration is compatible to v6.0 schema.
v3 to v1 tsc

2023-03-30 22:28 UTC, jan-vcapgemini requested changes
Change requests need to be addressed first.

2026-01-16 13:12 UTC, closed without merging