#1509 Restored original code for adaptTemplatesAndGenerate Test
devonfw/cobigen pull request #1631
Opened 2023-01-18 11:51 UTC by cedricarnauld123

Adresses/Fixes #<1509>.
#1622 
Implements

* Restored original code to test the adaptTemplates command in eclipse application and deleted faulty code

@devonfw/cobigen

2023-01-18 11:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/cobigen?pullRequest=1631) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/cobigen?pullRequest=1631) before we can accept your contribution.<br/><hr/>**Cedric Betom** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/cobigen?pullRequest=1631) it.</sub>

2023-01-24 11:06 UTC, jan-vcapgemini approved these changes

2023-01-24 11:06 UTC, jan-vcapgemini commented on cobigen-eclipse/cobigen-eclipse-test/src/main/java/com/devonfw/cobigen/eclipse/test/AdaptTemplatesTest.java
> -
Not so easy to follow changes, please put a reformat in a separate commit.

2023-02-07 10:50 UTC, EduardKrieger requested changes

2023-02-07 10:50 UTC, EduardKrieger commented on cobigen-eclipse/cobigen-eclipse-test/src/main/java/com/devonfw/cobigen/eclipse/test/AdaptTemplatesTest.java
> +     * TODO Before the templates are made available online, the update (download) command cannot be tested.
Open TODO

2023-03-28 10:34 UTC, EduardKrieger commented
Closed cause of CLA problems, the new PR #1654 will continue the issue.

2023-03-28 10:34 UTC, closed without merging